name: Deploy to GitHub Pages (gh-pages branch)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: .        # The folder to deploy (root of repo).
          clean: true
          commit-message: 'chore: deploy to gh-pages'
          token: ${{ secrets.GITHUB_TOKEN }}

# This workflow publishes the repository contents to a `gh-pages` branch using
# JamesIves/github-pages-deploy-action. After the first run, you may need to
# visit the repository's Pages settings to select `gh-pages` as the publishing
# source (or GitHub may switch automatically). This approach avoids the Pages
# internal artifact/upload flow that caused failures for some repositories.